# A generic, single database configuration.

[alembic]
# path to migration script directory
script_location = alembic

# template used to generate migration file names
file_template = %%(year)d_%%(month)02d_%%(day)02d_%%(hour)02d%%(minute)02d-%%(rev)s_%%(slug)s

sys_path = .

# max length of characters in slug
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a corresponding .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# version location specification; This defaults
# to alembic/versions. When using multiple version
# directories, initial revisions must be created with --version-path.
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# set to 'true' to search source_path recursively for
# files in version_locations
# recursive_version_locations = false

# sys.path path, prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file as
# well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for local time
# timezone =

# max length of characters in revision id
# revision_id_length = 12

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
